Rename "bindAddress" option to "address"
hoodiehq/hoodie pull request #591
Opened 2016-10-03 01:02 UTC by capellini

To align with hapi's server.connection options, rename Hoodie's `bindAddress` command line option to `address`.  Update documentation accordingly and log a deprecation warning.

Closes hoodihq/hoodie-server#496.

2016-10-03 01:06 UTC, capellini commented
Should I use `console.warn` to log the deprecation warning, or is there another logging utility that I should use?

2016-10-03 02:02 UTC, capellini commented on cli/options.js
> +    console.warn('The use of --bindAddress is deprecated. Use the --address option instead.')
Should I use `console.warn` to log the deprecation warning, or is there another logging utility that I should use?

If I should use `console.warn`, any idea how to mock it with `simple-mock` so the output doesn't display when testing?

2016-10-03 06:45 UTC, gr2m commented on cli/options.js
> +    console.warn('The use of --bindAddress is deprecated. Use the --address option instead.')
yes, we use `npmlog`.

Like this

```js
var log = require('npmlog')
// ...
log.warn('The use of --bindAddress is deprecated. Use the --address option instead.')
```

Then in tests you can do 

```js
require('npmlog').level = 'error'
```

2016-10-03 17:58 UTC, gr2m approved these changes
Thanks Rob, looking great! I would like to merge https://github.com/hoodiehq/hoodie/pull/590 first, and then rebase your PR on top of it, as #590 introduces lots of changes to tests

2016-10-03 18:02 UTC, capellini commented
> Thanks Rob, looking great! I would like to merge #590 first, and then rebase your PR on top of it, as #590 introduces lots of changes to tests

Ok.  Sounds good. :+1:

2016-10-03 18:45 UTC, varjmes approved these changes

2016-10-03 18:45 UTC, Charlotteis commented
lgtm

2016-10-04 03:15 UTC, capellini commented
Rebase complete.

In order to get 100% branch coverage, I needed to cover a case where `bindAddress` is converted into `address` and there also needs to be a case where we don't enter the `if` statement, so I had to change the test script to cover both cases.

Since I needed to create an instance of `yargs` with `bindAddress` and one without, I made a `createYargsMock` function.  Also, to avoid code duplication, I made a function to create our `getCliOptions` object for both test cases.

I'm not sure if there's a better way to accomplish what I did, but I'm looking forward to getting feedback!

2016-10-04 03:36 UTC, gr2m requested changes
besides the minor comment, this looks great 👍

2016-10-04 03:36 UTC, gr2m commented on test/unit/cli/options-test.js
> +  var yargsApi = {argv}
we don’t use es6 yet, can you change it to `{argv: arvg}` please?

2016-10-04 03:42 UTC, capellini commented on test/unit/cli/options-test.js
> +  var yargsApi = {argv}
Certainly.  Change made. Thanks!

2016-10-04 03:55 UTC, gr2m approved these changes
great work 👍

2016-10-04 03:56 UTC, merged

2016-10-04 04:03 UTC, gr2m commented
released in [v24.1.0](https://github.com/hoodiehq/hoodie/releases/tag/v24.1.0) 👍