Fix #609 - Hoodie default page not showing
hoodiehq/hoodie pull request #627
Opened 2016-10-31 14:03 UTC by benwhite-deltas

2016-10-31 15:23 UTC, gr2m requested changes
looking great, thanks! Just a few comments

2016-10-31 15:23 UTC, gr2m commented on cli/webroot-locator.js
> +var fs = require('fs')
🎨 can you please add an empty line below `module.exports = locateWebroot `

2016-10-31 15:23 UTC, gr2m commented on test/unit/cli/webroot-locator-test.js
> +    fsMock.existsSync.actions.length = 0
what is the `.actions.length = 0` for?

2016-10-31 15:23 UTC, gr2m commented on test/unit/cli/options-test.js
> +var mockWebrootLocator = simple.spy(function (arg) { return arg })
I didn’t know that you can stub `simple.spy`s, too, but for coherence with other code, can you do `simple.stub()` here and in the other places please?

2016-10-31 15:39 UTC, benwhite-deltas commented
actions.length = 0 is a way of resetting the stubbed behaviour, as spy.reset() only resets the logged calls. That way if we forget to change the behaviour between tests this should catch it and prevent a false positive.

Currently this fails, as public plugin currently determines the public webroot from the wrong config object path. Correcting this causes other tests to fail; I'll fix these tests as my next course of action.

2016-10-31 16:06 UTC, gr2m commented
but you don’t use `actions.length` anywhere else in the code? Am I missing something?

2016-10-31 16:39 UTC, benwhite-deltas commented
It's shorthand for emptying an array. I can change this to be a bit more explicit if required?

Deltas Software Ltd is a company registered in England &amp; Wales with registration number 08878020 at registered office Ordman House, 31 Arden Close, Bradley Stoke, Bristol, BS32 8AX. All rights reserved. No kittens were harmed in the sending of this email.

2016-11-01 10:31 UTC, benwhite-deltas commented
Rebased and pushed, ready for review, also pending yay/nay on the `actions.length = 0` array-emptying shorthand.

2016-11-01 16:12 UTC, benwhite-deltas commented on test/unit/cli/webroot-locator-test.js
> +    fsMock.existsSync.actions.length = 0
Comment moved from below: It's shorthand for emptying an array. I can change this to be a bit more explicit if required?

2016-11-02 01:04 UTC, gr2m requested changes
okay final comments. I can also fix it up myself if you are busy?

2016-11-02 01:04 UTC, gr2m commented on test/unit/cli/options-test.js
> +var mockWebrootLocator = simple.stub(function (arg) { return arg })
you can remove `function (arg) { return arg }`

2016-11-02 01:04 UTC, gr2m commented on test/unit/cli/webroot-locator-test.js
> +    fsMock.existsSync.actions.length = 0
okay I understand what `stub.actions` are now. I didn’t know one can chain `callbackWith`, `returnWith` and `throwWith`, that’s pretty cool! I would think that `stub.reset()` would remove these though, I’ll file an issue on simple-mock.

But please change the `actions.length = 0` to `actions = []`, it’s shorter and more readable

2016-11-02 01:04 UTC, gr2m commented on test/unit/cli/webroot-locator-test.js
> +    {fs: fsMock})
can you please change this to 

```js
var webrootLocator = proxyquire('../../../cli/webroot-locator', {
  fs: fsMock
})
```

2016-11-03 10:10 UTC, benwhite-deltas commented
Actioned review changes, and rebased ready for review.

2016-11-03 10:11 UTC, benwhite-deltas commented on test/unit/cli/options-test.js
> +var mockWebrootLocator = simple.stub(function (arg) { return arg })
Indeed I can! Done.

2016-11-03 10:11 UTC, benwhite-deltas commented on test/unit/cli/webroot-locator-test.js
> +    {fs: fsMock})
Changed. Agreed that that's clearer.

2016-11-03 17:00 UTC, gr2m approved these changes

2016-11-03 17:01 UTC, gr2m commented
beautiful work, thanks a ton

2016-11-03 17:02 UTC, merged

2016-11-04 17:26 UTC, brunopedroso commented
ooops.. should we check if the `server.paths` key is present? otherwise I'm forced to define it like
```
paths:{}
```
I'm using ember-hoodie...

2016-11-07 00:36 UTC, gr2m commented
it gets defaulted here: https://github.com/hoodiehq/hoodie/blob/047a8ff004538e68ccf2a89df33108fec505c3f3/server/index.js#L35-L40

2016-11-07 10:39 UTC, brunopedroso commented
yes, but only if I [dont define](https://github.com/hoodiehq/hoodie/blob/047a8ff004538e68ccf2a89df33108fec505c3f3/server/index.js#L26) `db.url`.

We're setting `db.url` here, and our app started to break on [this line](https://github.com/hoodiehq/hoodie/pull/627/files#diff-43557d6060003ff6997c94943ed23a82R11) just after I made the update. I had to define `paths:{}`...

Maybe that line could read like this?
```
var publicFolder = (options.config.paths && options.config.paths.public) || 'public'
```

2016-11-07 10:53 UTC, benwhite-deltas commented
FWIW, I'd be tempted to resolve this by moving [this clause](/hoodiehq/hoodie/blob/047a8ff004538e68ccf2a89df33108fec505c3f3/server/index.js#L35) alongside [this one](/hoodiehq/hoodie/blob/047a8ff004538e68ccf2a89df33108fec505c3f3/server/index.js#L19), removing the 'data' key and letting [this](/hoodiehq/hoodie/blob/047a8ff004538e68ccf2a89df33108fec505c3f3/server/index.js#L41) handle the data key.

2016-11-08 18:20 UTC, gr2m commented
@brunopedroso ooops that is definitely wrong

The way it’s currently handled is not very elegant. I’ve a lot of work stuff to catch up with and won’t be able to look into this, but if one of you could send a PR that will fix @brunopedroso’s problem, I’m happy to review and merge