removed start-hoodie
hoodiehq/hoodie pull request #681
Opened 2017-01-30 01:59 UTC by gautamkrishnar

fixes:https://github.com/hoodiehq/camp/issues/103

2017-01-30 02:04 UTC, gautamkrishnar commented
@gr2m :smile:

2017-01-30 17:11 UTC, gr2m requested changes

2017-01-30 17:11 UTC, gr2m commented on bin/setup.js
> -    packageJson.scripts[ 'start-hoodie' ] = 'hoodie'
sorry but removing `start-hoodie` entirely is not what we meant. We still want to keep it if the `start` script is set to something like `ember server` for example.

What we want is to add another `if () {}` statement in which we check if the current value of `packageJson.scripts[ 'start' ]` starts with `'hoodie'`. If it does, don’t do anything. If it does not, then set `packageJson.scripts[ 'start-hoodie' ] = 'hoodie'`. Does that make sense?

2017-01-30 17:18 UTC, gautamkrishnar commented
Okay. I will make changes soon...

2017-01-30 17:35 UTC, gautamkrishnar commented
@gr2m is just updated the code... Is this okay?

2017-01-30 17:46 UTC, gr2m approved these changes
great, thanks :)

2017-01-30 17:49 UTC, gr2m commented
@gautamkrishnar the tests are failing, which keeps us from merging your pull request. You can run `npm test` to see them, they are linting errors. You can see them on Travis, too: https://travis-ci.org/hoodiehq/hoodie/builds/196663948#L657

2017-01-31 09:25 UTC, gautamkrishnar commented
@gr2m fixed 🔪

2017-01-31 15:18 UTC, merged

2017-01-31 15:18 UTC, gr2m commented
cheers :)