Nimmi dev (Client API documentation editing branch) [WIP]
hoodiehq/hoodie pull request #706
Opened 2017-02-28 01:58 UTC by NimmiW

[Work-in-Progress branch] [Do not merge]
- hoodie client API page (WIP)
- hoodie Account API page (WIP)

2017-02-28 02:05 UTC, NimmiW commented
![image](https://cloud.githubusercontent.com/assets/26009680/23388472/68c431ec-fd88-11e6-89e4-bd74b1a73135.png)

How Can I revoke this automatic merge?

2017-02-28 08:43 UTC, fozy81 requested changes
Looks good, there's 'WIP
  <3<3<3' at the bottom of each document. Could you remove, thanks.

2017-03-01 01:08 UTC, pmbanugo reviewed
Since you're working on documentation, your commit messages should start with `docs: ..` I think.

### file: docs/api/client/hoodie.rst

#### Example

In the example section, this part of the code snippet could be modified? cc @gr2m

```
var Hoodie = require('@hoodie/client')

var hoodie = new Hoodie({
  url: 'https://myhoodieapp.com',
  PouchDB: require('pouchdb')
})
```

I use the global `hoodie` object from the client script so I don't do any of sort initialisation since I've been using Hoodie. I would suggest stating in the doc that there is a global object available if the script is referenced before script files it'll be used in and that initialisation code is optional. 

Does the hoodie client api work with Node? If so, aren't the APIs there similar to what we have for **hoodie-server**. If the hoodie-client will be used as a module in the browser, the snippet will need to change to use browser based module loaders and the initialisation code could be `var hoodie = new Hoodie({ url: 'http://localhost:4984', PouchDB: PouchDB });`. I don't know if we need to show sample snippet using different module loaders or just use ES Module. 

#### Constructor

This section is a bit confusing to me, in particular the type and description columns. Is the type a PouchDB object? I don't know if there is a type referred to as Constructor, but I know about the Constructor function. Trying to figure out that section got me confused as to what to if I need to instantiate a PouchDB object using the constructor, add some custom setting/configuration, and then pass that object as a reference to Hoodie, and what to do with a custom pouch build. Maybe we can explain this section differently and add sample snippet?

The other arguments except from url, with type set as string, aren't they object types with properties like `dbName` and `remote`? Options.dbName is set to hoodie.account.id? Why is that so?  

Also, the link in the description for store options points to account-client.  

@NimmiW My comments were to get some clarification from the maintainers and also to highlight my thoughts/observations I found from the ReadMe which if you update, would be needed to also do similar changes to the ReadMe.

Good job and Well done!

2017-03-01 01:21 UTC, gr2m commented
> Since you're working on documentation, your commit messages should start with docs: .. I think

That is correct, but don’t worry about commit messages while working on a pull request, we clean them up before we merge.

> I use the global hoodie object from the client script so I don't do any of sort initialisation since I've been using Hoodie. I would suggest stating in the doc that there is a global object available if the script is referenced before script files it'll be used in and that initialisation code is optional.

This is a bit tricky. It is true that if you load the hoodie client directly from the server at `http://localhost:8080/hoodie/client.js`, then you don’t need to do the initialisation yourself, it’s already done and you can use the `hoodie` object.

If you want to bundle the Hoodie client into your app bundle, then you will need to initialise it yourself as shown in the example. 

I would suggest we add both these information to the documentation.

For `hoodie.account`, I would remove the section on the constructor altogether and in the example on top remove the line `var account = new Account('https://example.com/account/api')`. And in all examples, replace `account.*` with `hoodie.account.*`

Does that all make sense?

2017-03-01 01:39 UTC, NimmiW commented
@pmbanugo okay I got what you said. but few minutes ago I did a commit without 'docs' tag. By the way I will use that tip in here after commits.

@gr2m Are removing the constructor part? in hoodie account doc? 

And as I understood so far, what I have to do is 

I would remove the section on the constructor altogether and in the example on top remove the line var account = new Account('https://example.com/account/api'). And in all examples, replace account.* with hoodie.account.*

Is that alright?

2017-03-01 01:42 UTC, NimmiW commented
Currently I am getting this error when I am trying to push my nimmi-dev branch to the origin repo.

![image](https://cloud.githubusercontent.com/assets/26009680/23442418/52c83840-fe4e-11e6-88a4-c69a664f52e6.png)

I pulled the changes from the repo also.

What can I do for this?

2017-03-01 02:15 UTC, gr2m commented
try `git push -f origin nimmi-dev`

2017-03-01 02:35 UTC, NimmiW commented
@gr2m yes pulling by force worked. :)

Currently I have make that change you made in account section

2017-03-01 04:20 UTC, NimmiW commented
@fozy81 I changed what you said

2017-03-01 04:25 UTC, gr2m commented
@NimmiW I think you still have to push your local changes? The pull request does not show any new commits yet

2017-03-01 04:40 UTC, NimmiW commented
@gr2m https://github.com/hoodiehq/hoodie/pull/706/commits 

There are 2 new commits 

![image](https://cloud.githubusercontent.com/assets/26009680/23446213/4e72c954-fe67-11e6-98e6-1ee9b0639dab.png)

2017-03-01 04:59 UTC, gr2m commented
my fault, all good

2017-03-01 07:45 UTC, fozy81 approved these changes

2017-03-01 07:46 UTC, fozy81 commented
@NimmiW thanks for the change :smile:

2017-03-01 08:19 UTC, gr2m requested changes

2017-03-01 08:19 UTC, gr2m commented on docs/api/client/hoodie.account.rst
> +<https://github.com/hoodiehq/hoodie-account-client/blob/master/admin>`_.
can you remove these two paragraphs? They 1st above is good enough

2017-03-01 08:19 UTC, gr2m commented on docs/api/client/hoodie.account.rst
> +    var account = new Account('https://example.com/account/api')
remove these two lines

2017-03-01 08:19 UTC, gr2m commented on docs/api/client/hoodie.account.rst
> +    account.on('signout', redirectToHome)
replace `account` with `hoodie.account`

2017-03-01 08:19 UTC, gr2m commented on docs/api/client/hoodie.account.rst
> +    })
remove `Constructor` section entirely

2017-03-01 08:19 UTC, gr2m commented on docs/api/client/hoodie.account.rst
> +account.ready
in the entire document, replace `account.` with `hoodie.account.`

2017-03-01 08:19 UTC, gr2m commented on docs/api/client/hoodie.account.rst
> +`Read-only`. Returns the account id. Cannot be accessed until the `account.ready <https://github.com/hoodiehq/hoodie-account-client#accountready>`_ promise resolved.
can we link to `hoodie.account.ready` within this document instead of linking to GitHub?

2017-03-01 08:19 UTC, gr2m commented on docs/api/client/hoodie.account.rst
> +    })
remove the constructor here, just start with `hoodie.account.validate`

2017-03-01 08:19 UTC, gr2m commented on docs/api/client/hoodie.account.rst
> +.. code:: json
should be code:: js

2017-03-01 08:19 UTC, gr2m commented on docs/api/index.rst
> +
can you remove the two empty lines again?

2017-03-01 09:23 UTC, NimmiW commented
@gr2m Ok gregor I got the Idea, I will make those changes in my next commit. And I it really interesting to collaborate with community.

2017-03-03 01:56 UTC, NimmiW commented
Hi all, I am again facing an issue in make html. If anyone can give me a help in that, pls leave a comment in issue https://github.com/hoodiehq/hoodie/issues/698

2017-03-03 01:58 UTC, NimmiW commented
@gr2m I still have to do the hyperlink change you mentioned. Since I am facing an inssue in rendering the html, I could not test it properly. I will correct that soon I fix my current issue.

2017-03-03 17:35 UTC, gr2m commented on docs/api/client/hoodie.account.rst
> +
can you make just one empty line like in the other examples?

2017-03-03 17:35 UTC, gr2m commented on docs/api/client/hoodie.account.rst
> +hoodie.accountcount.fetch
hoodie.account.fetch

2017-03-03 17:35 UTC, gr2m commented on docs/api/index.rst
> +
can you remove this empty line here?

2017-03-03 17:37 UTC, gr2m commented
@NimmiW I know this is one of your first PRs, and probably your biggest one yet. Just want to make sure you know that there is no problem at all if it takes a lot of iterations until you got everything right, this is totally normal :) You are doing a great job 👏

2017-03-03 18:20 UTC, NimmiW commented on docs/api/client/hoodie.account.rst
> +hoodie.accountcount.fetch
ok @gr2m :)

2017-03-03 18:20 UTC, NimmiW commented on docs/api/index.rst
> +
ok @gr2m :)

2017-03-03 18:24 UTC, NimmiW commented
@gr2m Pls excuse me for a while becoz I did not see the comment untill I do my recent push. Yes I will take my time and do the documentation. :)

2017-03-07 19:26 UTC, fozy81 approved these changes

2017-03-10 18:13 UTC, fozy81 approved these changes

2017-03-14 20:46 UTC, gr2m commented
Hey @NimmiW what’s the status, are you still working on it or is it ready for a final review? I think the `hoodie.log.rst` and `hoodie.connection-status.rst` are still pending, right?

2017-03-19 02:50 UTC, NimmiW commented
@gr2m I will create PR today for what I have done so far. there some areas in the readme files of Client APIs to be cleared. And completed so that I can add those missing areas to the documentation. As you mentioned `hoodie.log.rst` and `hoodie.connection-status.rst` are still pending. I did not went through them yet.

2017-03-19 06:16 UTC, NimmiW commented
@gr2m  and @fozy81 can you pls have a look on my PR? :) I want it to be reviewed

2017-03-19 16:36 UTC, fozy81 approved these changes

2017-03-21 06:56 UTC, gr2m requested changes

2017-03-21 06:56 UTC, gr2m commented on docs/conf.py
> +>>>>>>> 88aa9a317ddea8dc298489d8c68aa0a4f32ed9ea
can you remove the merge conflicts here?

2017-03-22 02:26 UTC, NimmiW commented on docs/conf.py
> +>>>>>>> 88aa9a317ddea8dc298489d8c68aa0a4f32ed9ea
ok @gr2m I will correct it :)

2017-03-22 09:11 UTC, pmbanugo commented on docs/api/client/hoodie.account.rst
> +Hooks
What do you think about explaining what a hook is and how it might be useful? 

I think we should provide an explanation for what a hook is, why one might need it and how it can be used (which the sample code already shows). Then stating that it's implemented with that npm package and providing the link to it

2017-03-22 18:05 UTC, gr2m commented on docs/api/client/hoodie.account.rst
> +Hooks
Good idea! I’d suggest we create a follow up issue for that so that we can merge this in, and then improve it later

2017-03-22 18:29 UTC, NimmiW commented on docs/api/client/hoodie.account.rst
> +Hooks
I did the changes @gr2m now we can merge it i think :)
@pmbanugo By the way yes me should definitely add the things you mentioned in anither issue

2017-03-22 18:59 UTC, pmbanugo commented on docs/api/client/hoodie.account.rst
> +Hooks
Yeah agreed. We can always make improvement and adjustment. Well done @NimmiW

2017-03-22 19:04 UTC, pmbanugo approved these changes

2017-03-23 02:46 UTC, NimmiW commented
Thank you @pmbanugo :) @gr2m or @pmbanugo can anyone of you create a new issue for the improvements of client API with details?

2017-04-02 08:34 UTC, NimmiW commented
Hi @gr2m @fozy81 @pmbanugo shall we merge this to master branch if all the things up to now are okay with API doc? :D

2017-04-02 17:50 UTC, gr2m approved these changes

2017-04-02 17:50 UTC, merged

2017-04-02 17:50 UTC, gr2m commented
great work @NimmiW 👏